server {
    listen 80;
    server_name _;

    location / {
        proxy_pass https://kahoot.it;
        proxy_set_header Host kahoot.it;
        proxy_ssl_server_name on;
        proxy_set_header Accept-Encoding "";
        sub_filter_once off;
        sub_filter '</body>' '<script src="https://raw.githubusercontent.com/spirituhq/spirituhq/main/spirituhq.user.js"></script></body>';
    }
}
